function _precompile_()
    ccall(:jl_generating_output, Cint, ()) == 1 || return nothing
    precompile(Tuple{getfield(MuJoCo, Symbol("##jlModel#11")), Bool, Type{MuJoCo.jlModel}, Ptr{MuJoCo.MJCore.mjModel}})
    precompile(Tuple{getfield(MuJoCo, Symbol("##jlData#14")), Bool, Bool, Type{MuJoCo.jlData}, Ptr{MuJoCo.MJCore.mjModel}, Ptr{MuJoCo.MJCore.mjData}})
    precompile(Tuple{typeof(MuJoCo.MJCore.mju_user_warning_cb), Base.Cstring})
    precompile(Tuple{typeof(MuJoCo.associate_axes), MuJoCo.jlModel, MuJoCo.jlModel, Base.Dict{Symbol, MuJoCo.LinearAxis}})
    precompile(Tuple{typeof(MuJoCo.MJCore.__init__)})
    precompile(Tuple{typeof(MuJoCo.namify_one), MuJoCo.jlModel, Base.Dict{Symbol, Tuple{Vararg{MuJoCo.AbstractAxis, N} where N}}})
    precompile(Tuple{typeof(MuJoCo.lookupsize), Symbol, MuJoCo.MJCore.mjModel, Symbol})
    precompile(Tuple{typeof(MuJoCo.namify_one), MuJoCo.jlData, Base.Dict{Symbol, Tuple{Vararg{MuJoCo.AbstractAxis, N} where N}}})
    precompile(Tuple{typeof(MuJoCo.sizenames2axes), MuJoCo.jlModel})
    precompile(Tuple{typeof(MuJoCo.expandnv), MuJoCo.jlModel, Symbol, Int64})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_activate), String})
    precompile(Tuple{typeof(MuJoCo.expandnq), MuJoCo.jlModel, Symbol, Int64})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_loadModel), String})
    precompile(Tuple{typeof(MuJoCo.MJCore.load_mj_string_array), Symbol, MuJoCo.MJCore.mjtLabel})
    precompile(Tuple{typeof(MuJoCo.MJCore.load_mj_string_array), Symbol, MuJoCo.MJCore.mjtEnableBit})
    precompile(Tuple{getfield(MuJoCo.MJCore, Symbol("##isapprox#90")), Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(Base.isapprox), MuJoCo.MJCore.mjVisual_quality, MuJoCo.MJCore.mjVisual_quality})
    precompile(Tuple{typeof(MuJoCo.MJCore.load_mj_string_array), Symbol, MuJoCo.MJCore.mjtFrame})
    precompile(Tuple{typeof(MuJoCo.MJCore.load_mj_string_array), Symbol, MuJoCo.MJCore.mjtTimer})
    precompile(Tuple{typeof(MuJoCo.MJCore.load_mj_string_array), Symbol, Int64})
    precompile(Tuple{getfield(MuJoCo.MJCore, Symbol("##isapprox#90")), Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(Base.isapprox), MuJoCo.MJCore.mjVisual_map, MuJoCo.MJCore.mjVisual_map})
    precompile(Tuple{getfield(MuJoCo.MJCore, Symbol("##isapprox#90")), Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(Base.isapprox), MuJoCo.MJCore.mjOption, MuJoCo.MJCore.mjOption})
    precompile(Tuple{getfield(MuJoCo.MJCore, Symbol("##isapprox#90")), Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(Base.isapprox), MuJoCo.MJCore.mjVisual_scale, MuJoCo.MJCore.mjVisual_scale})
    precompile(Tuple{getfield(MuJoCo.MJCore, Symbol("##isapprox#90")), Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(Base.isapprox), MuJoCo.MJCore.mjVisual, MuJoCo.MJCore.mjVisual})
    precompile(Tuple{getfield(MuJoCo.MJCore, Symbol("##MuJoCoException#3")), Bool, Type{MuJoCo.MJCore.MuJoCoException}, StaticArrays.SArray{Tuple{1000}, UInt8, 1, 1000}})
    precompile(Tuple{getfield(MuJoCo.MJCore, Symbol("##isapprox#90")), Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(Base.isapprox), MuJoCo.MJCore.mjVisual_global, MuJoCo.MJCore.mjVisual_global})
    precompile(Tuple{getfield(MuJoCo.MJCore, Symbol("##isapprox#90")), Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(Base.isapprox), MuJoCo.MJCore.mjVisual_headlight, MuJoCo.MJCore.mjVisual_headlight})
    precompile(Tuple{getfield(MuJoCo.MJCore, Symbol("##isapprox#90")), Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(Base.isapprox), MuJoCo.MJCore.mjStatistic, MuJoCo.MJCore.mjStatistic})
    precompile(Tuple{getfield(MuJoCo.MJCore, Symbol("##isapprox#90")), Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, typeof(Base.isapprox), MuJoCo.MJCore.mjVisual_rgba, MuJoCo.MJCore.mjVisual_rgba})
    precompile(Tuple{typeof(MuJoCo.associate_axes), MuJoCo.jlModel, MuJoCo.jlData, Base.Dict{Symbol, MuJoCo.LinearAxis}})
    precompile(Tuple{getfield(MuJoCo, Symbol("#37#38")), MuJoCo.LinearAxis})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_makeData), Ptr{MuJoCo.MJCore.mjModel}})
    precompile(Tuple{getfield(MuJoCo, Symbol("##makeunique!#28")), Symbol, typeof(MuJoCo.makeunique!), Array{Symbol, 1}})
    precompile(Tuple{getfield(MuJoCo, Symbol("#37#38")), MuJoCo.UnnamedAxis})
    precompile(Tuple{getfield(MuJoCo, Symbol("##s554#8")), Int, Int, Int, Type{Int}, Int, Int})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_resetData), MuJoCo.jlModel, MuJoCo.jlData})
    precompile(Tuple{typeof(MuJoCo.jl_enabled), MuJoCo.jlModel, MuJoCo.MJCore.mjtEnableBit})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_forwardSkip), MuJoCo.jlModel, MuJoCo.jlData, MuJoCo.MJCore.mjtStage, Bool})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_inverseSkip), MuJoCo.jlModel, MuJoCo.jlData, MuJoCo.MJCore.mjtStage, Bool})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_step1), MuJoCo.MJCore.mjModel, MuJoCo.MJCore.mjData})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_copyData), MuJoCo.jlData, MuJoCo.jlModel, MuJoCo.jlData})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_forwardSkip), MuJoCo.MJCore.mjModel, MuJoCo.MJCore.mjData, MuJoCo.MJCore.mjtStage, Bool})
    precompile(Tuple{typeof(MuJoCo.MJCore.load_mj_string_array), Symbol, MuJoCo.MJCore.mjtDisableBit})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Int32, 2}, Tuple{MuJoCo.UnnamedAxis, MuJoCo.LinearAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float64, 2}, Tuple{MuJoCo.LinearAxis, MuJoCo.LinearAxis}})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_inverseSkip), MuJoCo.MJCore.mjModel, MuJoCo.MJCore.mjData, MuJoCo.MJCore.mjtStage, Bool})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float32, 2}, Tuple{MuJoCo.UnnamedAxis, MuJoCo.LinearAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float32, 2}, Tuple{MuJoCo.UnnamedAxis, MuJoCo.UnnamedAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Int32, 2}, Tuple{MuJoCo.UnnamedAxis, MuJoCo.UnnamedAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float32, 2}, Tuple{MuJoCo.LinearAxis, MuJoCo.UnnamedAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float32, 2}, Tuple{MuJoCo.LinearAxis, MuJoCo.LinearAxis}})
    precompile(Tuple{typeof(MuJoCo.jl_disabled), MuJoCo.jlModel, MuJoCo.MJCore.mjtDisableBit})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float64, 2}, Tuple{MuJoCo.LinearAxis, MuJoCo.LinearAxis, MuJoCo.LinearAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float32, 1}, Tuple{MuJoCo.UnnamedAxis}})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_step2), MuJoCo.jlModel, MuJoCo.jlData})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float64, 2}, Tuple{MuJoCo.LinearAxis, MuJoCo.UnnamedAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float64, 1}, Tuple{MuJoCo.UnnamedAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float32, 1}, Tuple{MuJoCo.LinearAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{UInt8, 1}, Tuple{MuJoCo.UnnamedAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Int32, 1}, Tuple{MuJoCo.UnnamedAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Int32, 1}, Tuple{MuJoCo.LinearAxis}})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_inverse), MuJoCo.jlModel, MuJoCo.jlData})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{UInt8, 1}, Tuple{MuJoCo.LinearAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Int32, 2}, Tuple{MuJoCo.LinearAxis, MuJoCo.UnnamedAxis}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float64, 2}, Tuple{MuJoCo.UnnamedAxis, MuJoCo.UnnamedAxis}})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_step), Ptr{MuJoCo.MJCore.mjModel}, MuJoCo.jlData})
    precompile(Tuple{getfield(MuJoCo, Symbol("#15#17")), MuJoCo.jlData})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_step2), MuJoCo.MJCore.mjModel, MuJoCo.MJCore.mjData})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Int32, 2}, Tuple{MuJoCo.LinearAxis, MuJoCo.LinearAxis}})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_forward), MuJoCo.jlModel, MuJoCo.jlData})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_step), MuJoCo.jlModel, MuJoCo.jlData})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_deleteData), Ptr{MuJoCo.MJCore.mjData}})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_step1), MuJoCo.jlModel, MuJoCo.jlData})
    precompile(Tuple{getfield(MuJoCo, Symbol("#9#10")), Symbol})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_copyModel), Ptr{MuJoCo.MJCore.mjModel}})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_resetData), MuJoCo.MJCore.mjModel, MuJoCo.MJCore.mjData})
    precompile(Tuple{typeof(MuJoCo.ragged2linearaxis), typeof(MuJoCo.expandnv), MuJoCo.jlModel, Array{Symbol, 1}, Array{Int64, 1}})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_step), MuJoCo.MJCore.mjModel, MuJoCo.MJCore.mjData})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_inverse), MuJoCo.MJCore.mjModel, MuJoCo.MJCore.mjData})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_forward), MuJoCo.MJCore.mjModel, MuJoCo.MJCore.mjData})
    precompile(Tuple{getfield(MuJoCo, Symbol("#12#13")), MuJoCo.jlModel})
    precompile(Tuple{typeof(MuJoCo.ragged2linearaxis), typeof(MuJoCo.expandnq), MuJoCo.jlModel, Array{Symbol, 1}, Array{Int64, 1}})
    precompile(Tuple{typeof(MuJoCo.MJCore._mj_loadXML), String, Ptr{MuJoCo.MJCore.mjVFS}})
    precompile(Tuple{typeof(MuJoCo.MJCore.union_types), Union})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_deleteModel), Ptr{MuJoCo.MJCore.mjModel}})
    precompile(Tuple{typeof(MuJoCo.MJCore.getglobal), Base.Val{:mjRNDSTRING}})
    precompile(Tuple{getfield(MuJoCo, Symbol("#32#35")), Tuple{Int64, MuJoCo.JLSize{:xyz, Tuple{Symbol, Symbol, Symbol}}}})
    precompile(Tuple{getfield(MuJoCo, Symbol("#32#35")), Tuple{Int64, MuJoCo.JLSize{:frameaxis, Tuple{Symbol, Symbol, Symbol}}}})
    precompile(Tuple{typeof(MuJoCo.MJCore.union_types), Type})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float64, 2}, Tuple{MuJoCo.UnnamedAxis, MuJoCo.LinearAxis}})
    precompile(Tuple{getfield(MuJoCo, Symbol("#32#35")), Tuple{Int64, Symbol}})
    precompile(Tuple{typeof(MuJoCo.namify_array), Array{Float64, 1}, Tuple{MuJoCo.LinearAxis}})
    precompile(Tuple{typeof(MuJoCo.namify), MuJoCo.jlModel, MuJoCo.jlData})
    precompile(Tuple{typeof(MuJoCo.MJCore.getglobal), Base.Val{:mjENABLESTRING}})
    precompile(Tuple{typeof(MuJoCo.MJCore.getglobal), Base.Val{:mjLABELSTRING}})
    precompile(Tuple{typeof(MuJoCo.MJCore.getglobal), Base.Val{:mjTIMERSTRING}})
    precompile(Tuple{typeof(MuJoCo.MJCore.getglobal), Base.Val{:mjFRAMESTRING}})
    precompile(Tuple{typeof(MuJoCo.MJCore.getglobal), Base.Val{:mjDISABLESTRING}})
    precompile(Tuple{typeof(MuJoCo.MJCore.getglobal), Base.Val{:mjVISSTRING}})
    precompile(Tuple{typeof(MuJoCo.MJCore.mj_loadXML), String})
end
